# Generated by Django 3.0.2 on 2020-01-29 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200129_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
